metabrainz/picard-docs

source/acknowledgements.rst

**Summary**
This is a…
**Reason for the Change**
Additional text to encourage contributions from ordinary users.
**Description of the Change**
Self evident.

Additional text to encourage contributions.

---

.github/workflows/test.yml
.github/workflows/test_build_publish.yml

**Summary**
This is a…
**Reason for the Change**
Other maintainers may be pushing changes to the `master` branch, causing the documentation to be published.  "Bob Swift" was hard coded as the committed by name, which is no longer appropriate.
**Description of the Change**
Remove hard coded name from commits when publishing documentation.
**Additional Action Required**
None.

Clean up github workflow files

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md
README.md

**Summary**
This is a…
**Reason for the Change**
Help encourage contributions from users.
**Description of the Change**
Include Sophist's text that encourages contributions in the README and CONTRIBUTING files.  Also add note about ePub files.
**Additional Action Required**
None.

Add Sophist's encourage contributions text to README and CONTRIBUTING

---

source/introduction.rst

This is a…
Provide more information for people who are new to tagging and / or Picard.

Improve introduction for people new to tagging and / or new to Picard

---

source/getting_started/download.rst

This is a…
Clarify that ordinary users should use stable release executables.

Prioritise platform install options.

---

.github/workflows/test.yml

This is a…
A recent change accidentally disabled the checks when a PR was entered against the `master` branch.
Re-enable the checks..
None.

Re-enable testing on pull requests to 'master'

---

_templates/versions.html
conf.py
index.html.template
setup.py
source/troubleshooting/missing_tags.rst
version_links.js.template

This is a…
Previously the system did not allow serving earlier versions of the documentation.
Changes to accommodate publishing multiple versions.  Also correct a bad link in one document file.
None.

Support publishing multiple versions of the documentation.

---

publish.py

This is a…
Publish code was failing when trying to copy the files to the release directory.  Suspect a timing problem because rerunning the script (locally) it did not fail.
Add small time delays between copy operations and remove the exception handling to allow full exception messages to be displayed.
Cross your fingers.  :wink:

Add time delays and remove exception handling

---

publish.py

This is a…
Publishing was still failing.
This is an update to create the version directory if required.
None.

Create missing directory as required.

---

.github/CONTRIBUTING.md
source/acknowledgements.rst
source/contributing.rst
source/epub.rst
source/index.rst
source/introduction.rst
source/pdf.rst

This is a…
Needed to make the contribution section a bit more inviting and informative, and to provide acknowledgement to the contributors (to help encourage more contributors to participate).
Split the Contribution and Acknowledgement sections, and expand each.
None.

Update contributing and acknowledgement info

---

source/config/options_tags_compatibility_id3.rst
source/faq/faq_file_formats.rst
source/troubleshooting/missing_tags.rst
source/variables/tags_advanced.rst
source/variables/tags_basic.rst
source/variables/variables_other_information.rst

This is a…
There were some links to pages on the picard.musicbrainz.org site that have now been included in the documentation.
Change the external links to now point to the appropriate pages within the documentation.
None.

Use internal links where available.

---

TODO.md

These are suggestions - using the PR approval process as a means of getting feedback and gaining consensus. So please feel free to disagree.
The biggest suggestion is the revamp of the multi-language approach. I am entirely unclear how the current Github structure facilitates translations into other languages. It appears to intend that this is done using Transifex, but I am really uncertain whether this is a good approach for this rather than manual translation due to its piecemeal approach - mainly because sentences or phrases in a text document (rather than message snippets in an application) may have a far greater contextual relevance to one another, but partly because (unlike app terminology) documentation phrases don't typically recur and so piecemeal translation is inefficient too.. …

Add some suggestions to the ToDo list.

---

source/acknowledgements.rst
source/contributing.rst
source/epub.rst
source/index.rst
source/pdf.rst

This is a…
Needed to clarify the order of the contributors in the list and what was meant by a contributor.  Also needed to elevate the acknowledgements of the contributions.
Added explanation of contributors list and order in alphabetical order.  Elevate the acknowledgements section to be even with contributing section so that it appears in the TOC.
None.

Clarify contributors roles

---

source/config/options_interface.rst

Added missing documentation for the "use built-in search" interface option

Document the "use built-in search" user interface option

---

source/acknowledgements.rst
source/glossary.rst

This is a…
* Remove the extra MBID references and ensure that links titles contain the name of the entity instead of a raw MBID value
* Add definition for medium
* Definition tweaks

Update glossary terms

---

conf.py
source/config/configuration.rst
source/config/options_cover_art_providers.rst
source/config/options_interface.rst
source/config/options_network.rst
source/troubleshooting/no_coverart.rst
source/usage/attach_disc_id.rst
source/usage/coverart.rst
source/usage/match.rst
source/variables/tags_basic.rst
source/variables/variables.rst
source/variables/variables_basic.rst
source/variables/variables_file.rst

This is a…
Prepare the documentation for Picard 2.5.
Overview of changes:
- Make release once Picard 2.5 final has been released
- Update screenshots

Documentation for Picard 2.5

---

conf.py
source/technical/command_line_common.txt

This is a…
Prepare documentation for 2.5.1 release
Not much change, but a new `--no-player` command line option

Picard 2.5.1

---

_locale/fr/LC_MESSAGES/appendices/tag_mapping.po
_locale/fr/LC_MESSAGES/variables/tags_basic.po
appendices/tag_mapping.rst
tag_mapping.py
variables/tags_basic.rst

This is a…
New tag added in https://github.com/metabrainz/picard/pull/1738
Add new tag information to the documentation.
None.

Add 'director' tag and associated tag mapping

---

appendices/keyboard_shortcuts.rst
index.rst

This is a…
Picard provides many keyboard shortcuts, not all of them visible via the UI. This provides an documentation page listing the shortcuts.
Add a table to list all keyboard shortcuts available in the main window and also special keyboard shortcuts used by the script editor.
There are some more specific UI elements that might implement additional shortcuts, such as the list editors used at various places or the tag editing dialog. Need to review those, but we could document them here as well.

Appendix: Keyboard shortcuts help

---

_locale/fr/LC_MESSAGES/functions/func_replacemulti.po
functions/func_replacemulti.rst
functions/list_by_type.rst

This is a…
A new `$replacemulti()` function is being added to Picard in PR https://github.com/metabrainz/picard/pull/1781
Add documentation for the new `$replacemulti()` function.
None.

Add documentation for new $replacemulti() function

---

appendices/plugins_api.rst

This is a…
Anything that helps us understand why you are making this change goes here.
What problem are you trying to fix? What does this change address?
The details, considerations, or other interesting points of your change.
Other than merging your change, do you want / need us to do anything else
with your change? This could include reviewing a specific part of your PR.

Describe formatting of PLUGIN_DESCRIPTION with Markdown / HTML

---

_locale/fr/LC_MESSAGES/appendices/keyboard_shortcuts.po
_locale/fr/LC_MESSAGES/functions/func_map.po
_locale/fr/LC_MESSAGES/functions/func_replacemulti.po
appendices/keyboard_shortcuts.rst
appendices/plugins_api.rst
functions/func_map.rst
functions/func_replacemulti.rst
functions/list_by_type.rst

This is a…
The $map() function is being updated to automatically remove empty elements.
Update the documentation to reflect the revised behavior of the `$map()` function.
Do not merge until https://github.com/metabrainz/picard/pull/1790 is merged.

Update $map() to note automatic removal of empty elements from output

---

extending/scripts.rst

This is a…
Add some examples for tagging scripts to help users getting started and solve some common issues
Add a couple of scripting examples with explanation. This is from my personal list of useful scripting snippets, mostly the result of forum discussions and user requests.

extending/scripts: Added some scripting examples

---

functions/func_performer.rst

This is a…
Additional regex support was added to the `performer()` function.
Add information about the changes, including additional examples..
Translation.

Add regex support changes to performer() function

---

appendices/keyboard_shortcuts.rst

This is a…
New file naming script editor page added.
Document the keyboard shortcuts for the new page.
Update translations.

Add keyboard shortcuts for file naming script editor

---

_locale/de/LC_MESSAGES/variables/tags_basic.po
_locale/de/LC_MESSAGES/variables/variables_basic.po
_locale/fr/LC_MESSAGES/variables/tags_basic.po
_locale/fr/LC_MESSAGES/variables/variables_basic.po
_locale/gettext/variables/tags_basic.pot
_locale/gettext/variables/variables_basic.pot
_locale/pt_BR/LC_MESSAGES/variables/tags_basic.po
_locale/pt_BR/LC_MESSAGES/variables/variables_basic.po
variables/tags_basic.rst
variables/variables_basic.rst

This is a…
See the discussion at https://tickets.metabrainz.org/browse/PICARD-2280
Remove the `discid` tag.  Update the `musicbrainz_discid` tag.  Add the `_musicbrainz_discids` variable.
Translations.

Update information regarding disc id tags and variables

---

functions/func_cleanmulti.rst
functions/list_by_type.rst

This is a…
A new `$cleanmulti()` function is being added in https://github.com/metabrainz/picard/pull/2029
Add documentation for the new function.

Add `$cleanmulti()` function documentation

---

config/options_before_tagging.rst

This is a…
Document the new "Fix missing seekpoints for FLAC files" option from PICARD-2411

Document "Fix missing seekpoints for FLAC files" option

---

config/options_before_tagging.rst
epub.rst
functions/func_cleanmulti.rst
functions/func_substr.rst
functions/list_by_type.rst
index.rst
usage/attach_disc_id.rst
usage/retrieve_lookup_cd_steps.txt
workflows/workflow_cd.rst
workflows/workflow_extractor_log.rst
workflows/workflows.rst

This is a…
Changes that are being implemented in Picard v2.8.
Update the documentation for changes that are being implemented in Picard v2.8:

Updates for Picard v2.8

---

config/options_filerenaming.rst
config/options_profiles.rst
faq/faq_file_formats.rst
getting_started/status_icons.rst

This is a…
The goal is to remove a few typos.
Light modification of a few reStructuredText source files.
None.

Minor fixes

---

requirements.txt

This is a…
Building the documentation with Python 3.10 fails.
Update to latest Sphinx 4.5.
I tested this locally and it seems to work. But Sphinx 4 brought a few changes (https://www.sphinx-doc.org/en/master/changes.html#release-4-0-0-released-may-09-2021) and something might be broken.

Updated to Sphinx 4.5

---

functions/func_gt.rst
functions/func_gte.rst
functions/func_lt.rst
functions/func_lte.rst
functions/func_max.rst
functions/func_min.rst
functions/list_by_type.rst

This is a…
Pull requext https://github.com/metabrainz/picard/pull/2110 revised the `$gt()`, `$gte()`, `$lt()` and `$lte()` scripting functions, and added two new functions `$max()` and `$min()`.
Update the pages for the revised functions and add pages for the new functions.
Once merged, the translation files will need to be updated.  Note that these changes are not planned to be included in Picard until version 3.0.

Update $lt, $lte, $gt and $gte functions.  Add $max and $min functions

---

faq/faq_file_formats.rst

Fix a typo

---

about_picard/acknowledgements.rst
appendices/keyboard_shortcuts.rst

This is a…
New keyboard shortcut addition in picard for `Show more details`
Added new shortcut in `Metadata view` section
None

Update docs for PICARD-2580(keyboard shortcut for Show more details)
