- source/config/configuration.rst
This is a…
Give a little more context to the Options intro by repeating an existing screenshot.
> Add a screenshot to the intro Options section

- source/technical/tag_mapping_common.txt
This is a…
Add documentation of RIFF INFO mapping to tag mapping table. Compare https://github.com/metabrainz/picard/blob/master/picard/formats/wav.py#L46
> Add RIFF INFO to tag mapping

- source/config/configuration.rst
- source/usage/coverart.rst
Document small additions to the UI in 2.5:
- Manual selection of cover art via file open dialog
- Context menu entry and double click for loading files from file browser
> Picard 2.5 small UI additions

- source/config/options_cover_art_providers.rst
- source/config/options_interface.rst
- source/config/options_network.rst
This is a…
There have been several changes in the options for Picard 2.5:
- Support for SOCKS proxy
- Support for configuring a network timeout
- Cover art provider for approved URLs has been renamed for clarity (we probably could also remove it, but let's do this for a later time)
- Option to use system theme
- Built-in search is the new default
> Update options for Picard 2.5

- source/variables/tags_basic.rst
- source/variables/variables.rst
- source/variables/variables_basic.rst
- source/variables/variables_file.rst
This is a…
Picard 2.5 will allow using file specific variables in tagging scripts.
Moved the special file variables to a separate page for clarity. Removed the notes that those are only available in naming script, but add a warning that this is the case in older versions of Picard
> 2.5 update file variables docs

- source/usage/match.rst
This is a…
Picard 2.5 allows to drag and drop multiple files on tracks and have them assigned to multiple tracks.
Add a note to the "Matching Files to Tracks" section describing the drag and drop behavior and how to disable this temporarily.
> Document Picard 2.5 behavior of dropping multiple files onto a track

- source/faq/faq.rst
- source/faq/faq_usage_macos_startup_error.rst
This is a…
There have been frequent reports about the macOS app getting an error message about the app being damaged. To all we can tell this is not caused by the app, but a problem with macOS Gatekeeper. As this is outside our control have an FAQ entry to help users get around this.
See https://tickets.metabrainz.org/browse/PICARD-1763 and related discussions
> Add an FAQ entry about app being shown as damaged on macOS

- source/usage/tags_from_file_names.rst
This is a…
Picard 2.5 now properly supports setting hidden variables from the "Tags from file names" dialogue. This is especially useful if you want to not match parts of the file name 
Extend the "Dags from file names" documentation with a paragraph "Ignoring parts of the file name"
> tags_from_file_names additions for Picard 2.5

- source/variables/variables_basic.rst
This is a…
The variables _discpregap, _pregap and _datatrack have been undocumented
Extended the basic variables docs.
> Documented variables _discpregap, _pregap and _datatrack

- source/variables/variables_other_information.rst
This is a…
In https://picard-docs.musicbrainz.org/en/variables/variables_other_information.html the handling of custom tags is explained. This currently misses MP4, for which Picard also allows writing custom tags since version 2.3.
Rework the documentation how Picard handles unknown tags.
> Document usage of custom MP4 tags, update docs on custom tags

- .gitignore
- 404.html
- 404_template.html
This is a…
The location of the `scripting.html` file was changed, causing the link from Picard to break.  This was reported in issue #66.
Update the redirection logic in the `404.html` file to redirect calls to the old location of `scripting.html` to its new location.  Fixes #66. 
None.
> Add redirection to new location of scripting.html

- _locale/fr/LC_MESSAGES/extending/scripting.po
- _locale/fr/LC_MESSAGES/functions/func_rreplace.po
- _locale/fr/LC_MESSAGES/functions/func_rsearch.po
- extending/scripting.rst
- functions/func_rreplace.rst
- functions/func_rsearch.rst
This is a…
There seems to be some confusion with users entering regular expressions.  If they don't understand the need to escape certain characters, it can be a source of frustration.
Add a note to the `$rreplace()` and `$rsearch()` scripting functions about the need to escape certain characters to prevent Picard from trying to interpret them as part of the script functions.
Confirm that all characters required to be escaped are listed in the note.  The note includes the backslash and the opening and closing parentheses.  Should it also include the comma and dollar sign?
> Add note to regular expression functions about escaping '\', '(' and ')'

- _locale/fr/LC_MESSAGES/getting_started/download.po
- setup.py
This is a…
Google Translate will often break restructured text links, roles and directives by changing the formatting by adding or removing spaces.  Occasionally these errors get past the manual checking process, and have to be repaired later after already having been published.
Add a rudimentary check to the options in `setup.py` to check the `*.po` files for restructured text errors.  This is called as:
```
setup.py test po
```
Note that this won't catch every error, but it can usually find the majority of them.
This PR also updates one translation file that was found to have a link error using this checking.
This is a quick hack and has not been optimized.  It should be used for local testing only, and not in the GitHub Actions testing.
~~Eventually I may update this to build and check …
> Add rudimentary testing of RST in *.po files

- faq/faq_usage.rst
- getting_started/download.rst
This is a…
The Linux Snap version does not have access to removable drives by default, but can be enabled. As this might not be clear that this is the case and that this can be changed document this.
Document how to grant Picard access to removable drives on the download page. Also add a FAQ entry.
> download: Clarify giving Picard Snap access to removable media

- _locale/fr/LC_MESSAGES/genindex.po
- _locale/fr/LC_MESSAGES/sphinx.po
- conf.py
This is a…
Some things appeared slightly unnatural in the French navigation (left sidebar and pagination buttons).
We would not select the French language (la langue française) but French as language (je choisis le français comme langue).
Also for consistency, I put infinitive verb.
*Précédent* (Previous) was OK but *Prochain* (Next) was quite strange.
So I replaced by the translation of previous page and next page.
I was reviewing the bigger FR files when I stopped because I wondered if maybe those changes have to be done in something like Transifex, instead of a PR.
So I committed only the small files, in case it's not the way to go.
I am never keen to use Transifex, BTW.
> Quick FR fixes

- _locale/fr/LC_MESSAGES/config/options_location.po
- config/options_location.rst
This is a…
Use of the cover art file name mask template is not well understood.  See the discussion on the [Community Forum](https://community.metabrainz.org/t/cover-art-archive-setting-use-the-first-image-type-as-the-filename-behavior-inverted/521941/9).
Provide additional detail and examples.
None.
> Expand description of coverart filename mask option

- _locale/fr/LC_MESSAGES/appendices/keyboard_shortcuts.po
- _locale/fr/LC_MESSAGES/appendices/keyboard_shortcuts_pdf.po
- appendices/keyboard_shortcuts_pdf.rst
- appendices/pdf_appendices.rst
This is a…
Add keyboard shortcut information to the PDF version of the Picard User Guide, and include French language translations.
Add `*.rst` file to build for PDF output.  Replace macOS special symbols with key text for the PDF output because of build failures due to unknown UTF-8 characters.  Add French translation files.
Continue to look into Sphinx problems building the PDF files with the macOS UTF-8 special symbols.
> Add keyboard shortcuts to PDF builder.  Add French translation.

- _locale/fr/LC_MESSAGES/appendices/keyboard_shortcuts.po
- _static/css/extra.css
- appendices/keyboard_shortcuts.rst
- conf.py
This is a…
Make use of the `:kbd:` role for designating keyboard shortcuts.
Use the `:kbd:` role for the keyboard shortcuts page, and also add some CSS styling for nicer rendering of those.
Here is a screenshot how this renders on Firefox on Windows:
Also this formatting applies to other places where `:kbd:` role is being used in text, e.g.:
I could not check how this ends up in the epub or PDF. epub should just render the same as the normal HTML I guess. And in the Latex generated documents the `:kbd:`  role likely just is rendered also in a monospaced font.
> Render keyboard shortcuts with kbd role

- _locale/fr/LC_MESSAGES/tutorials/multiple_release_countries.po
- _locale/fr/LC_MESSAGES/variables/variables_basic.po
- epub.rst
- index.rst
- tutorials/acoustid.rst
- tutorials/multiple_release_countries.rst
- tutorials/tutorials.rst
- variables/variables_basic.rst
This is a…
A new `_release_countries` variable was added in Picard v2.3.1 but never included in the documentation.
Added `_releasecountries` to the list of variables provided, and add a tutorial (originally posted by outsidecontext in the forums) explaining how this could be used.
Once the final wording has been approved, the French translation files will need to be updated prior to merging this PR.
> Multiple release country tutorial

- functions/func_countryname.rst
- functions/list_by_type.rst
This is a…
A new `$countryname()` function is being added to Picard in https://github.com/metabrainz/picard/pull/1828
This provides the documentation for the new function.
Translation once the `next_version_2.7` branch is merged into the `master` branch.
> Add documentation for $countryname() function

- config/options_filerenaming_editor.rst
- config/options_scripting.rst
This is a…
There was no documentation regrading the use of unicode characters in script.
Add information about entering unicode characters into scripts.  Also add information about highlighting and tooltips to tagging script documentation.
Translation.
> Add information about the use of unicode characters in scripts.

- _locale/gettext/config/options_filerenaming.pot
- config/options_filerenaming.rst
This is a…
There are often questions about whether Picard can also move subdirectories (e.g. containing additional images, etc.)  when moving files to a new release directory.  It is not clear in the documentation that this is possible.  See the discussion on the [Community Forum](https://community.metabrainz.org/t/can-i-automate-moving-a-subfolder-ie-artwork-when-moving-and-creating-my-new-album-folders/550628).
Add information about also moving subdirectores by specifying them in the "Move additional files" option settings.
Translations.
> Add note about using "Move additional files" to also move subdirectories

- usage/submit_acousticbrainz.rst
This is a…
Changes made in https://github.com/metabrainz/picard/pull/1902 require that the files be matched to MusicBrainz releases and saved before submitting to AcousticBrainz.
Add explanation of the new requirement to the documentation.
Translations.
> Add note about saving the files before submitting to acousticbrainz

- functions/func_slice.rst
This is a…
Some of the examples for the $slice() function were missing a comma and would actually show as errors in the script because of incorrect number of arguments
Add the missing commas.
None.
> Add missing commas in $slice() examples

- config/options_filerenaming.rst
- config/options_filerenaming_editor.rst
- tutorials/naming_script.rst
This is a…
File naming tutorial page didn't explain how to get started writing a new file naming script, and the file naming script options didn't refer to the tutorial.
Add links between the file naming editor and tutorial pages.  Also minor text changes to match the button text in the dialog.
Update translation POT and PO files.
> Add links between filenaming editor and tutorial.

- functions/func_copymerge.rst
This is a…
In https://github.com/metabrainz/picard/pull/2020 a new option is being added to the `$copymerge()` function.
Add information about the new option.
Do not merge until the change in Picard has been released, currently planned for Picard v2.8.
Once merged, update the translation files.
> Add option to `$copymerge()` function

- extending/scripting.rst
- functions/func_get.rst
This is a…
Tag names containing a hyphen cannot be accessed using the "%" method, but must use the `$get()` function.  This is not currently explained in the documentation.
Add a note based on outsidecontext's response to a question in the [Community Forum](https://community.metabrainz.org/t/help-with-field-data-entry/568128/2).
> Add note about accessing tags with hyphens in the tag name

- _locale/de/LC_MESSAGES/variables/variables_basic.po
- _locale/fr/LC_MESSAGES/variables/variables_basic.po
- _locale/gettext/variables/variables_basic.pot
- _locale/nb_NO/LC_MESSAGES/variables/variables_basic.po
- _locale/nl/LC_MESSAGES/variables/variables_basic.po
- _locale/pt_BR/LC_MESSAGES/variables/variables_basic.po
- variables/variables_basic.rst
This is a…
The `%_musicbrainz_tracknumber%` variable was never included in the documentation.
**EDIT:** The `%_recording_comment%` was also missing.
Add documentation for the `%_musicbrainz_tracknumber%` variable.
**EDIT:** Also add the definition for the `%_recording_comment%` valiable.
None.
> Add the `%_musicbrainz_tracknumber%` variable

- functions/func_substr.rst
This is a…
The `end` parameter of the `$substr()` function was made truly optional in https://github.com/metabrainz/picard/pull/2039
Update the documentation to clarify that the parameter can be omitted completely.
Hold merging this until Picard v2.8 has been released.
Once merged, the translation files need to be updated.
> Make the `$substr()` end parameter optional

- epub.rst
- index.rst
- usage/attach_disc_id.rst
- usage/retrieve_lookup_cd_steps.txt
- workflows/workflow_cd.rst
- workflows/workflow_extractor_log.rst
- workflows/workflows.rst
This is a…
Changes in https://github.com/metabrainz/picard/pull/2048 added the ability to use an EAC or XLD ripper log file to lookup a release.
**EDIT:** Updated to include ability to use Whipper log files that was added in https://github.com/metabrainz/picard/pull/2056
Add documentation of the use of EAC / XLD / Whipper logs for CD lookup.
> PICARD-2408: Add documentation of the use of EAC / XLD logs for CD lookup

- variables/tags_basic.rst
This is a…
The internal tag name is "musicbrainz_trackid", not "musicbrainz_releasetrackid": "musicbrainz_trackid",". The latter is just the name written out to some formats, because "musicbrainz_trackid" has already been used for the recording ID for historic reasons
> Remove "musicbrainz_releasetrackid" from basic tag list

- 404_template.html
This is a…
Improve url remapping to try to avoid 404s.  Current tests and remapping did not properly handle some cases.
Improve automatic url remapping:
- Test and correct invalid version number such as 'v2.6.3' rather than 'v2.6' and to add missing 'v' if necessary.  Automatically redirect to the latest version if an invalid `major.minor` such as '99.99' is provided when the latest release is '2.7'.
- Automatically remap ReadTheDocs version specifiers 'latest' and 'stable' to the appropriate versions.
- Automatically try to serve a language matching the preferred languages in the user's browser settings if there is no language specified in the url.  For example, `https://picard-docs.musicbrainz.org/variables/tags_basic.html` will be served as …
> Improve url remapping tests

- about_picard/acknowledgements.rst
- appendices/command_line.rst
- epub.rst
- getting_started/pdf_starting.rst
- getting_started/starting.rst
- index.rst
- pdf.rst
- usage/command_processing.rst
- usage/exec_commands.rst
This is a…
New features were introduced in https://github.com/metabrainz/picard/pull/2116 and https://github.com/metabrainz/picard/pull/2173
Add information about the use of the single instance and passing files and command information to the running instance for processing.  Add discussion of available executable commands and batch command processing from a command text file.
This PR builds upon the changes made by @skelly37 in https://github.com/metabrainz/picard-docs/pull/174 which has been superceded and the changes merged into this PR.
> Single instance operation and executable command processing

- faq/faq_file_formats.rst
- usage/retrieve.rst
- usage/retrieve_lookup_cd.rst
- usage/retrieve_lookup_cd_steps.txt
- workflows/workflow_extractor_log.rst
This is a…
Parsing of **fre:ac** logs is being added to version 3 of Picard in https://github.com/metabrainz/picard/pull/2158, and **dBpoweramp** logs added in https://github.com/metabrainz/picard/pull/2151#event-7453440343.
Update the list of ripper logs that Picard can process for lookup.  ~Also some minor refactoring to clarify the index entries for the page.~
**Note:** The restructuring was reverted because Sphinx does not include index items entered in an `index` **directive** in the translation POT and PO files.  Only entries from an `index` **role** are included in the translation files.  This was reported in https://github.com/sphinx-doc/sphinx/issues/976 and the issue was closed; however, the issue does not appear to have been corrected.
Once merged, the translation files will …
> Add fre:ac and dBpoweramp to ripper logs parsed

- faq/faq_usage.rst
This is a…
In PICARD-2600 the user was trying to use Picard together with rclone on Windows to access and directly tag files stored in Google cloud storage. rclone is providing a virtual file system, but in order to be completely compatible with all file operations done by Picard (mostly seeking in files to find the tags and using `os.path.realpath`) some options need to be set correctly when using the `rclone mount command`.
Add a FAQ entry specific to using rclone on Windows with the proper options.
> Add FAQ entry about using rclone on Windows to mount cloud storage

- variables/tags_advanced.rst
- variables/variables_advanced.rst
This is a…
New variables are being added in https://github.com/metabrainz/picard/pull/2188
Add descriptions for the new `_lyricistsort` and `_writersort` variables.
Do not merge until https://github.com/metabrainz/picard/pull/2188 has been merged. Once approved and merged, translation files will need to be updated.
> Add `_lyricistsort` and `_writersort` variables

- functions/func_copy.rst
This is a…
There is often confusion regarding the `$copy()` command because, unlike most commands, the `source` argument is specified without being enclosed by percent signs.
Add a note to specifically point out this difference.
One approved, the translation files will need to be updated.
> Add note to `$copy()` about source not enclosed by percent signs.

- appendices/keyboard_shortcuts.rst
This is a…
As discussed in PICARD-2581 it should be clarified that the keyboard shortcuts documented are in addition to the standard keyboard shortcuts provided by the user's operating system.
Add a brief note that the shortcuts are in addition to the standard operating system shortcuts.
> PICARD-2581: Add note about standard keyboard shortcuts

- variables/variables_file.rst
This is a…
Two new file variables (`_file_created_timestamp` and `_file_modified_timestamp`) were added in https://github.com/metabrainz/picard/pull/2194
Add descriptions for the new file variables.
Translation files will need to be updated.
> Add variables `_file_created_timestamp` and `_file_modified_timestamp`

- functions/func_copymerge.rst
- functions/func_dateformat.rst
- functions/func_datetime.rst
This is a…
Similar notes on scripting functions were displayed or worded differently.  The different wording causes more translation strings.
Standardize wording and presentation of similar notes on related functions.
> Standardize notes between related functions

- usage/exec_commands.rst
This is a…
Initial documentation for the CLI executable commands is somewhat sparse.  Also the functionality of the `QUIT` command is being changed slightly in https://github.com/metabrainz/picard/pull/2192 and needs to be documented.
Expand the descriptions of the CLI executable commands, and update the `QUIT` command description to include the changes.
Do not merge until https://github.com/metabrainz/picard/pull/2192 has been accepted and merged.
> Expand documentation for the executable commands

- variables/tags_basic.rst
- variables/variables_file.rst
This is a…
Some concerns were raised in the #metabrainz IRC channel by @reosarevok about **MusicBrainz Identifier** not being clearly identified as also being referred to as **MBID**.  Suggested that this could also be linked to the documentation on the MusicBrainz site for more information.
Current wording seemed to indicate that some tag information such as **lyrics** was provided by MusicBrainz.  This is incorrect.
Add notes about MBID and include a link to the documentation on the MusicBrainz website.  Clarify that some information is **not** provided by MusicBrainz.  Some reformatting and general cleanup.
> General tag description cleanup

- config/options_filerenaming_editor.rst
This is a…
The functionality of the file naming script editor was modified in https://github.com/metabrainz/picard/pull/2201 to allow editing of all scripts, and allowing the selection of system preset scripts as a starting point for new scripts.
The documentation is being updated to reflect the new changes to the file naming script editor.
Once merged, the translation POT files will need to be updated.
> Update file naming script editor documentation

- appendices/plugins_api.rst
This is a…
In https://github.com/metabrainz/picard/pull/2199 the `PLUGIN_USER_GUIDE_URL` variable was added to the plugin api.
Update the plugin api documentation to include the new variable.
Once merged, the translation POT files will need to be updated.
> Add `PLUGIN_USER_GUIDE_URL` variable to plugins api documentation

- config/options_tags_compatibility_id3.rst
- faq/faq_config.rst
- variables/tags_basic.rst
This is a…
Picard 2.9 will change to ID3v2.4 by default, see https://github.com/metabrainz/picard/pull/2209 and PICARD-900
Update texts discussing ID3 versions to reflect the new default.
> Update texts to reflect switch to ID3v2.4 by default

- about_picard/introduction.rst
- conf.py
- requirements.txt
- usage/attach_disc_id.rst
- usage/submit_acoustid.rst
This is a…
This change embeds tutorial videos from the MetaBrainz Youtube channel that aerozol recently made. This can help users who prefer the visual guidance through the program over the textual description.
The following videos are embedded on the relevant pages:
- What is MusicBrainz Picard
- How to add a DiscID to MusicBrainz
- What are AcoustIDs and how to submit them
The videos are embedded using the [`sphinxcontrib.youtube`](https://github.com/sphinx-contrib/youtube) module.
I set the `:privacy_mode:` flag for embedding the videos. This is supposed to load the videos via youtube-nocookie.com to avoid the Google cookies. However, in my tests this did currently not work as intended, see https://github.com/sphinx-contrib/youtube/issues/57
> Embed video tutorials into corresponding doc pages

- about_picard/introduction.rst
- index.rst
- setup.py
- tutorials/v_attach_disc_id.rst
- tutorials/v_introduction.rst
- tutorials/v_submit_acoustid.rst
- usage/attach_disc_id.rst
- usage/submit_acoustid.rst
This is a…
Further to the discussion in https://github.com/metabrainz/picard-docs/pull/196
Create a new top-level section on the website only to more promenently display the available video tutorials.
Once merged, the translation templates will need to be updated.
> Create new top level section for video tutorials

- appendices/tag_mapping.rst
- tag_mapping.py
- variables/tags_advanced.rst
This is a…
In https://github.com/metabrainz/picard/pull/2206/ a new `releasedate`  tag got added.
Extend the tag mapping table and add a note about its use. Also add to advanced variables documentation.
> Add releasedate tag to tag mapping table

- variables/variables_basic.rst
This is a…
New "series" variables are being added to Picard as part of [PICARD-711](https://tickets.metabrainz.org/browse/PICARD-711).
See: https://github.com/metabrainz/picard/pull/2213
Add descriptions for the new variables.
Once merged, translation templates need to be updated.
> Add new "series" variables

- about_picard/introduction.rst
- conf.py
- usage/attach_disc_id.rst
- usage/submit_acoustid.rst
This is a…
The epub file build includes the video tutorial pages as extra pages (not in the table of contents), placing them at the end of the document after the Index section.
Add the video tutorial pages to the list of excluded files when building the epub file.  Use a helper function to automatically identify the files to exclude.
None.
> Exclude video tutorial pages from epub file

- variables/tags_advanced.rst
- variables/tags_basic.rst
This is a…
The `director` tag definition is being changed in https://github.com/metabrainz/picard/pull/2276
Update the tag definition in the documentation to match the change in Picard.
Do not merge until the change is merged into Picard.  Once merged, the translation files will need to be updated.
> Update the definition of the `director` tag to include Audio Director

- _extensions/taggerscript.py
- conf.py
- pylintrc
- setup.py
- stage_translation_files.py
- tag_mapping.py
This is a…
There were problems using `sphinx-intl` for updating the `.po` files, so the preferred processer has been changed to `msgmerge` (part  of the standard `gettext` suite) with a fallback to using `sphinx-intl` if `msgmerge` isn't available.
There were problems with the translation file staging script staging files when the only change was the translation strings were wrapped to a different length.  In addition, the processing logic was inefficient.
All python scripts showed errors when analyzed by `isort`, `flake8` and/or `pylint`.
General improvements and cleanup of the python scripts:
- disable deprecated configuration item
- update string formatting to use f-strings
- remove deprecated utf string type designator
- update string formatting to use f-strings
- reorganize and …
> General improvements and python script cleanup

- _locale/de/LC_MESSAGES/appendices/command_line.po
- _locale/fr/LC_MESSAGES/appendices/command_line.po
- _locale/gettext/appendices/command_line.pot
- _locale/nb_NO/LC_MESSAGES/appendices/command_line.po
- _locale/nl/LC_MESSAGES/appendices/command_line.po
- _locale/pt_BR/LC_MESSAGES/appendices/command_line.po
- appendices/command_line.rst
This is a…
An addional command line option was added in https://github.com/metabrainz/picard/pull/2316
Add the information for the new `-a, --audit` command line option.  Also add the information for the `--no-crash-dialog` command line option that was added 2 years ago but was never documented.
> Update command line options

- _locale/de/LC_MESSAGES/troubleshooting/troubleshooting.po
- _locale/fr/LC_MESSAGES/troubleshooting/troubleshooting.po
- _locale/gettext/troubleshooting/troubleshooting.pot
- _locale/nb_NO/LC_MESSAGES/troubleshooting/troubleshooting.po
- _locale/nl/LC_MESSAGES/troubleshooting/troubleshooting.po
- _locale/pt_BR/LC_MESSAGES/troubleshooting/troubleshooting.po
- troubleshooting/troubleshooting.rst
This is a…
Improve instructions for obtaining debug log output under various conditions as suggested by @phw  in https://github.com/metabrainz/picard-docs/pull/211
Update the Troubleshooting section to include details on getting "Debug" logs, normally and when crashes occur.
Update translation files
> include details on getting "Debug" logs, normally and when crashes occur

- troubleshooting/troubleshooting.rst
This is a…
There is a [broken link in documentation.](https://tickets.metabrainz.org/browse/PICARD-2808)
The link pointing to the quick start guide in the documentation was broken, therefore it needed to be corrected.
Fixed the url pointing to quick start guide and set it to : https://picard.musicbrainz.org/quick-start/
No additional action required.
> fixed quick start guide link

- config/configuration.rst
This is a…
I was trying to address was how to access the plugins for Picard , which was discussed in the thread here : https://community.metabrainz.org/t/how-to-run-plugins-on-picard-as-a-developer/674175 .I think that clearly mentioning the access to plugins or options menu to MacOs users would be more intuitive and useful .
Jira Ticket _(optional)_ - [PICARD-2818](https://tickets.metabrainz.org/browse/PICARD-2818)
I essentially added the path of action which would lead to the user reaching the plugins selection via the options menu in a MacOs environment , extending the guide to the windows based systems . adjoining with the pr are screenshots demonstrating the working of the pathway updated in the pr . 
img 1 . Python --> Preferences 
img 2. plugins selection 
No Additional Action …
> Extend docs to include macOs options access

- about_picard/acknowledgements.rst
- appendices/tag_mapping.rst
- tag_mapping.py
- variables/tags_basic.rst
This is a…
This adds the synced lyrics tag mapping. 
So far only id3 is supported.
> Add mapping for synced lyrics tag

- functions/func_dateformat.rst
This is a…
One of the examples in the `$dateformat()` function had an incorrect argument.
Change incorrect argument `myd` to `ymd`.
> Fix typo in $dateformat() function examples

- variables/variables_basic.rst
This is a…
New variables are being added in https://github.com/metabrainz/picard/pull/2628
Add the new variables to the documentation.
> PICARD-3055: Add new `_albumartists_countries` and `_artists_countries` variables

- functions/func_rsearch.rst
This is a…
In PICARD-3072 / PICARD-3065 a new group parameter got added to the `$rsearch` function. This was backported to the 2.x branch and will be part of the 2.14 release.
Doc-Ticket: PICARD-3068
Document the `$group` parameter. Compare also https://github.com/metabrainz/picard/commit/16b943df155b30e18ab71cb8fae6a312cb3a991d
> PICARD-3068: Document group parameter for $rsearch (PICARD-3072)

- translators.py
This is a…
There was no consolidated means of extracting translation completion by locale (language) and a clean and unique list of translation contributors.
Add a script to produce translation information:
- Extract a list of translation contributors from the commit history.
- Provide a list of translators including the locales (languages) to which they contributed.
- Provide a list of translators and the total translation information (number of strings translated, total number of strings, and percent completion)for each local (language).
None.
> Add a script to produce translation information
